name: 😴 Stale branches detection

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1' # Every Monday at 10:00 UTC
    
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        persist-credentials: true

    - name: Stale bot
      run: |
        git fetch --all
        git for-each-ref --sort=-committerdate refs/remotes/origin/ --format='%(refname:short) - %(committerdate:iso8601)' > branches.txt
        
        now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "Today is $now"

        threshold=$(date -u -d "$now - 30 days" +"%Y-%m-%dT%H:%M:%SZ")
        echo "Threshold is $threshold"

        echo "Branches older than 30 days:"
        while IFS= read -r line; do
          branch=$(echo $line | cut -d' ' -f1)
          commit_date=$(echo $line | cut -d' ' -f3)
          if [[ "$branch" != "origin/main" && "$commit_date" < "$threshold" ]]; then
            branch_name=$(echo $branch | sed 's|^origin/||')
            echo "Current branch: $branch_name"

            branch_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/branches/$branch_name")
            author_email=$(echo $branch_info | jq -r '.commit.commit.author.email')
            author_date=$(echo $branch_info | jq -r '.commit.commit.author.date')
            last_commit_date=$(date -d "$author_date" +"%Y-%m-%d")
            days_inactive=$(( ( $(date -d "$now" +%s) - $(date -d "$author_date" +%s) ) / 86400 ))
            echo "Inactivity in days: $days_inactive"

            user_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/search/users?q=${author_email}+in:email")
            github_username=$(echo $user_info | jq -r '.items[0].login')
            echo "Last commit by: $github_username"

            comment_body="\
        Ping @${github_username} \n\
        Branch [**${branch_name}**](https://github.com/${{ github.repository }}/tree/${branch_name}) is inactive since **${last_commit_date}** (**${days_inactive} days ago**).\n\
        Please either [remove it](https://github.com/${{ github.repository }}/branches/all) or [open a pull request](https://github.com/${{ github.repository }}/compare/main...${branch_name}?expand=1) to merge it.\n\n\
        Thanks for your contribution !"

            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -X POST \
              -d "{\"body\": \"${comment_body}\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/1/comments"
          fi
        done < branches.txt